export type PlanetName = 'Mercury' | 'Venus' | 'Mars' | 'Jupiter' | 'Saturn' | 'Uranus' | 'Neptune';

export interface PlanetConditionsLocation { latitude: number; longitude: number; timezone: string; }
export interface PlanetCondition {
  name: PlanetName; symbol: string; visible: boolean; status: 'good' | 'possible' | 'not-recommended'; tier: 'primary' | 'low' | 'advanced';
  reason: string; bestTime: Date | null; bestAltitude: number | null; direction: string | null; magnitude: number | null;
  rise: Date | null; set: Date | null; visibleFrom: Date | null; visibleUntil: Date | null;
}
export interface PlanetConditionsData { sunset: Date; sunrise: Date; planets: PlanetCondition[]; }
type OrbitalElements = { N: number; i: number; w: number; a: number; e: number; M: number };
const DEG = Math.PI / 180; const RAD = 180 / Math.PI; const DAY_MS = 86400000;
const PLANETS: Record<PlanetName, { symbol: string; elements: (d: number) => OrbitalElements; nakedEye: boolean }> = {
  Mercury: { symbol: '☿', elements: mercuryElements, nakedEye: true }, Venus: { symbol: '♀', elements: venusElements, nakedEye: true },
  Mars: { symbol: '♂', elements: marsElements, nakedEye: true }, Jupiter: { symbol: '♃', elements: jupiterElements, nakedEye: true },
  Saturn: { symbol: '♄', elements: saturnElements, nakedEye: true }, Uranus: { symbol: '⛢', elements: uranusElements, nakedEye: false }, Neptune: { symbol: '♆', elements: neptuneElements, nakedEye: false },
};
function mercuryElements(d: number): OrbitalElements { return { N: 48.3313 + 3.24587e-5*d, i: 7.0047 + 5e-8*d, w: 29.1241 + 1.01444e-5*d, a: .387098, e: .205635 + 5.59e-10*d, M: 168.6562 + 4.0923344368*d }; }
function venusElements(d: number): OrbitalElements { return { N: 76.6799 + 2.4659e-5*d, i: 3.3946 + 2.75e-8*d, w: 54.891 + 1.38374e-5*d, a: .72333, e: .006773 - 1.302e-9*d, M: 48.0052 + 1.6021302244*d }; }
function marsElements(d: number): OrbitalElements { return { N: 49.5574 + 2.11081e-5*d, i: 1.8497 - 1.78e-8*d, w: 286.5016 + 2.92961e-5*d, a: 1.523688, e: .093405 + 2.516e-9*d, M: 18.6021 + .5240207766*d }; }
function jupiterElements(d: number): OrbitalElements { return { N: 100.4542 + 2.76854e-5*d, i: 1.303 - 1.557e-7*d, w: 273.8777 + 1.64505e-5*d, a: 5.20256, e: .048498 + 4.469e-9*d, M: 19.895 + .0830853001*d }; }
function saturnElements(d: number): OrbitalElements { return { N: 113.6634 + 2.3898e-5*d, i: 2.4886 - 1.081e-7*d, w: 339.3939 + 2.97661e-5*d, a: 9.55475, e: .055546 - 9.499e-9*d, M: 316.967 + .0334442282*d }; }
function uranusElements(d: number): OrbitalElements { return { N: 74.0005 + 1.3978e-5*d, i: .7733 + 1.9e-8*d, w: 96.6612 + 3.0565e-5*d, a: 19.18171 - 1.55e-8*d, e: .047318 + 7.45e-9*d, M: 142.5905 + .011725806*d }; }
function neptuneElements(d: number): OrbitalElements { return { N: 131.7806 + 3.0173e-5*d, i: 1.77 - 2.55e-7*d, w: 272.8461 - 6.027e-6*d, a: 30.05826 + 3.313e-8*d, e: .008606 + 2.15e-9*d, M: 260.2471 + .005995147*d }; }
function daysSince2000(date: Date): number { return date.getTime()/DAY_MS - 10957.5; }
function normalizeDegrees(value: number): number { return ((value%360)+360)%360; }
function solveKepler(meanAnomaly: number, eccentricity: number): number { let E=meanAnomaly+eccentricity*Math.sin(meanAnomaly)*(1+eccentricity*Math.cos(meanAnomaly)); for(let i=0;i<5;i++) E-=(E-eccentricity*Math.sin(E)-meanAnomaly)/(1-eccentricity*Math.cos(E)); return E; }
function heliocentricEcliptic(elements: OrbitalElements) { const E=solveKepler(normalizeDegrees(elements.M)*DEG,elements.e); const xv=elements.a*(Math.cos(E)-elements.e); const yv=elements.a*Math.sqrt(1-elements.e*elements.e)*Math.sin(E); const v=Math.atan2(yv,xv); const r=Math.hypot(xv,yv); const N=elements.N*DEG,i=elements.i*DEG,w=elements.w*DEG; return {x:r*(Math.cos(N)*Math.cos(v+w)-Math.sin(N)*Math.sin(v+w)*Math.cos(i)),y:r*(Math.sin(N)*Math.cos(v+w)+Math.cos(N)*Math.sin(v+w)*Math.cos(i)),z:r*Math.sin(v+w)*Math.sin(i)}; }
function earthElements(d: number): OrbitalElements { return {N:0,i:0,w:282.9404+4.70935e-5*d,a:1,e:.016709-1.151e-9*d,M:356.047+.9856002585*d+180}; }
function planetEquatorial(date: Date, planet: PlanetName) { const d=daysSince2000(date), earth=heliocentricEcliptic(earthElements(d)), target=heliocentricEcliptic(PLANETS[planet].elements(d)); const xh=target.x-earth.x,yh=target.y-earth.y,zh=target.z-earth.z,ob=(23.4393-3.563e-7*d)*DEG; const xe=xh,ye=yh*Math.cos(ob)-zh*Math.sin(ob),ze=yh*Math.sin(ob)+zh*Math.cos(ob); return {ra:normalizeDegrees(Math.atan2(ye,xe)*RAD)/15,dec:Math.atan2(ze,Math.hypot(xe,ye))*RAD}; }
function localSiderealTime(date: Date, longitude: number): number { const jd=date.getTime()/DAY_MS+2440587.5,gst=normalizeDegrees(280.46061837+360.98564736629*(jd-2451545))/15; return normalizeDegrees(gst+longitude/15); }
function altitudeAndAzimuth(date: Date, latitude: number, longitude: number, ra: number, dec: number) { const H=(localSiderealTime(date,longitude)-ra)*15*DEG,lat=latitude*DEG,d=dec*DEG; const altitude=Math.asin(Math.max(-1,Math.min(1,Math.sin(lat)*Math.sin(d)+Math.cos(lat)*Math.cos(d)*Math.cos(H))))*RAD; const azimuth=normalizeDegrees(Math.atan2(Math.sin(H),Math.cos(H)*Math.sin(lat)-Math.tan(d)*Math.cos(lat))*RAD+180); return {altitude,azimuth}; }
function solarPosition(date: Date, latitude: number, longitude: number) { const d=daysSince2000(date),earth=heliocentricEcliptic(earthElements(d)),ob=(23.4393-3.563e-7*d)*DEG; const ra=normalizeDegrees(Math.atan2(-earth.y*Math.cos(ob)+earth.z*Math.sin(ob),-earth.x)*RAD)/15,dec=Math.atan2(-earth.y*Math.sin(ob)-earth.z*Math.cos(ob),Math.hypot(earth.x,earth.y))*RAD; return altitudeAndAzimuth(date,latitude,longitude,ra,dec); }
function findCrossing(start: Date,end: Date,latitude: number,longitude: number,targetAltitude: number): Date|null { let a=start.getTime(),b=end.getTime(),fa=solarPosition(new Date(a),latitude,longitude).altitude-targetAltitude; if(fa*(solarPosition(new Date(b),latitude,longitude).altitude-targetAltitude)>0)return null; for(let i=0;i<25;i++){const m=(a+b)/2,f=solarPosition(new Date(m),latitude,longitude).altitude-targetAltitude;if(fa*f<=0)b=m;else{a=m;fa=f;}} return new Date((a+b)/2); }
function localDateParts(date: Date,timezone: string) { const p=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),v=Object.fromEntries(p.map(x=>[x.type,x.value])); return {year:Number(v.year),month:Number(v.month),day:Number(v.day)}; }
function zonedTimeToDate(year:number,month:number,day:number,hour:number,minute:number,timezone:string):Date { const guess=new Date(Date.UTC(year,month-1,day,hour,minute)),p=new Intl.DateTimeFormat('en-US',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(guess),v=Object.fromEntries(p.map(x=>[x.type,x.value])),asUtc=Date.UTC(Number(v.year),Number(v.month)-1,Number(v.day),Number(v.hour),Number(v.minute)); return new Date(guess.getTime()+(guess.getTime()-asUtc)); }
function solarCrossing(dateStart:Date,dateEnd:Date,latitude:number,longitude:number,target:number,rising:boolean):Date|null { const step=10*60000; let previousTime=dateStart,previous=solarPosition(dateStart,latitude,longitude).altitude-target; for(let t=dateStart.getTime()+step;t<=dateEnd.getTime();t+=step){const currentTime=new Date(t),current=solarPosition(currentTime,latitude,longitude).altitude-target;if((rising&&previous<=0&&current>0)||(!rising&&previous>=0&&current<0))return findCrossing(previousTime,currentTime,latitude,longitude,target);previousTime=currentTime;previous=current;} return null; }
function directionName(azimuth:number):string { return ['North','Northeast','East','Southeast','South','Southwest','West','Northwest'][Math.round(azimuth/45)%8]; }
function practicalThreshold(planet:PlanetName,sunAltitude:number):number { if(planet==='Venus')return sunAltitude<=-2?8:12; if(planet==='Jupiter')return sunAltitude<=-6?10:14; if(planet==='Saturn')return sunAltitude<=-6?12:16; if(planet==='Mars')return sunAltitude<=-6?10:15; if(planet==='Mercury')return sunAltitude<=-8?8:12; return 10; }
function scanPlanet(planet:PlanetName,location:PlanetConditionsLocation,dayStart:Date,dayEnd:Date):PlanetCondition { const def=PLANETS[planet]; let bestTime:Date|null=null,bestAltitude:number|null=null,bestAzimuth=0,rise:Date|null=null,set:Date|null=null,visibleFrom:Date|null=null,visibleUntil:Date|null=null,practicalMinutes=0,lowMinutes=0,previousAltitude=altitudeAndAzimuth(dayStart,location.latitude,location.longitude,...Object.values(planetEquatorial(dayStart,planet)) as [number,number]).altitude; const step=5*60000; for(let t=dayStart.getTime();t<=dayEnd.getTime();t+=step){const time=new Date(t),eq=planetEquatorial(time,planet),h=altitudeAndAzimuth(time,location.latitude,location.longitude,eq.ra,eq.dec),sun=solarPosition(time,location.latitude,location.longitude).altitude,threshold=practicalThreshold(planet,sun),dark=sun<=(planet==='Venus'?-2:-6),practical=h.altitude>=threshold&&dark,low=h.altitude>=0&&dark&&!practical;if(previousAltitude<=0&&h.altitude>0&&!rise)rise=time;if(previousAltitude>=0&&h.altitude<0&&!set)set=time;if(bestAltitude===null||h.altitude>bestAltitude){bestAltitude=h.altitude;bestTime=time;bestAzimuth=h.azimuth;}if(practical){practicalMinutes+=5;if(!visibleFrom)visibleFrom=time;visibleUntil=time;}if(low)lowMinutes+=5;previousAltitude=h.altitude;}
  const visible=practicalMinutes>=(planet==='Mercury'?10:20),lowVisible=!visible&&lowMinutes>=10,advanced=!def.nakedEye&&(visible||lowVisible); const tier:PlanetCondition['tier']=advanced?'advanced':lowVisible?'low':'primary'; const status:PlanetCondition['status']=visible?(def.nakedEye&&practicalMinutes>=45&&(bestAltitude??0)>=20?'good':'possible'):lowVisible?'possible':'not-recommended';
  let reason='It is below the horizon for much of the night.'; if(advanced)reason='This planet is far too faint to see without a strong telescope.'; else if(visible)reason=(bestAltitude??0)>=20?'It gets high enough above the horizon to be a good target.':'It is in the sky tonight, but it stays fairly low.'; else if(lowVisible)reason='It is very low in the sky, so trees and buildings may hide it.'; else if(rise&&rise>dayStart)reason='It rises later in the day; check the rise time below.'; else if(bestAltitude!==null&&bestAltitude<0)reason='It stays below the horizon during the night.'; else if(planet==='Mercury'||planet==='Venus')reason='It stays close to the Sun, making it tricky to spot.';
  return {name:planet,symbol:def.symbol,visible:visible||lowVisible,status,tier,reason,bestTime,bestAltitude,direction:bestTime?directionName(bestAzimuth):null,magnitude:null,rise,set,visibleFrom,visibleUntil}; }
export function calculatePlanetConditions(location:PlanetConditionsLocation,now=new Date()):PlanetConditionsData|null { if(!Number.isFinite(location.latitude)||!Number.isFinite(location.longitude)||(location.latitude===0&&location.longitude===0))return null; const timezone=location.timezone.includes('Local timezone')?Intl.DateTimeFormat().resolvedOptions().timeZone:location.timezone,{year,month,day}=localDateParts(now,timezone),dayStart=zonedTimeToDate(year,month,day,0,0,timezone),nextDay=new Date(dayStart.getTime()+DAY_MS),sunset=solarCrossing(dayStart,nextDay,location.latitude,location.longitude,-.833,false)??solarCrossing(dayStart,nextDay,location.latitude,location.longitude,0,false),sunrise=solarCrossing(dayStart,nextDay,location.latitude,location.longitude,-.833,true)??solarCrossing(dayStart,nextDay,location.latitude,location.longitude,0,true); if(!sunset||!sunrise)return null; return {sunset,sunrise,planets:(Object.keys(PLANETS) as PlanetName[]).map(p=>scanPlanet(p,location,dayStart,nextDay))}; }
export function formatPlanetTime(date:Date,timezone:string):string { const safe=timezone.includes('Local timezone')?Intl.DateTimeFormat().resolvedOptions().timeZone:timezone; return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZone:safe}).format(date); }
export function formatPlanetHour(date:Date,timezone:string):string { const safe=timezone.includes('Local timezone')?Intl.DateTimeFormat().resolvedOptions().timeZone:timezone; return new Intl.DateTimeFormat('en-US',{hour:'numeric',timeZone:safe}).format(date); }
export function formatPlanetAltitude(altitude:number|null):string { return altitude===null?'':`${Math.round(altitude)}° high`; }
